# -*- coding: utf-8 -*-
"""Text_Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfRVQ68FcBuk94PTU6Y2nmOZG9hDRkk1
"""

!pip install datasets evaluate transformers[sentencepiece]

!pip install "transformers<5"

!pip install rouge_score

!pip install bert-score

### TEXTS TO SUMMARIZE

text_robots = """Robots are physical agents that perform tasks by manipulating the physical world. To do so, they are equipped with effectors such as legs, wheels, joints, and grippers. Effectors are
designed to assert physical forces on the environment. When they do this, a few things may
happen: the robot’s state might change (e.g., a car spins its wheels and makes progress on the
road as a result), the state of the environment might change (e.g., a robot arm uses its gripper
to push a mug across the counter), and even the state of the people around the robot might
change (e.g., an exoskeleton moves and that changes the configuration of a person’s leg; or
a mobile robot makes progress toward the elevator doors, and a person notices and is nice
enough to move out of the way, or even push the button for the robot).
Sensor Robots are also equipped with sensors, which enable them to perceive their environment.
Present-day robotics employs a diverse set of sensors, including cameras, radars, lasers, and
microphones to measure the state of the environment and of the people around it; and gyroscopes,
strain and torque sensors, and accelerometers to measure the robot’s own state.
Maximizing expected utility for a robot means choosing how to actuate its effectors to
assert the right physical forces—the ones that will lead to changes in state that accumulate as
much expected reward as possible. Ultimately, robots are trying to accomplish some task in
the physical world.
Robots operate in environments that are partially observable and stochastic: cameras
cannot see around corners, and gears can slip. Moreover, the people acting in that same
environment are unpredictable, so the robot needs to make predictions about them.
Robots usually model their environment with a continuous state space (the robot’s position
has continuous coordinates) and a continuous action space (the amount of current a
robot sends to its motor is also measured in continuous units). Some robots operate in highdimensional
spaces: cars need to know the position, orientation, and velocity of themselves
and the nearby agents; robot arms have six or seven joints that can each be independently
moved; and robots that mimic the human body have hundreds of joints.
Robotic learning is constrained because the real world stubbornly refuses to operate faster
than real time. In a simulated environment, it is possible to use learning algorithms (such as
the Q-learning algorithm described in Chapter 23) to learn in a few hours from millions of
trials. In a real environment, it might take years to run these trials, and the robot cannot risk
(and thus cannot learn from) a trial that might cause harm. Thus, transferring what has been
learned in simulation to a real robot in the real world—the sim-to-real problem—is an active
area of research. Practical robotic systems need to embody prior knowledge about the robot,
the physical environment, and the tasks to be performed so that the robot can learn quickly
and perform safely.
Robotics brings together many of the concepts we have seen in this book, including probabilistic
state estimation, perception, planning, unsupervised learning, reinforcement learning,
and game theory. For some of these concepts robotics serves as a challenging example
application. For other concepts this chapter breaks new ground, for instance in introducing
the continuous version of techniques that we previously saw only in the discrete case.
"""

text_networks = """Network applications are everywhere. Any time you browse the Web, send an
email message, or play an online game, you are using a network application.
Interestingly, all network applications are based on the same basic programming
model, have similar overall logical structures, and rely on the same programming
interface.
Network applications rely on many of the concepts that you have already
learned in our study of systems. For example, processes, signals, byte ordering,
memory mapping, and dynamic storage allocation all play important roles. There
are new concepts to master as well. You will need to understand the basic clientserver programming model and how to write client-server programs that use the
services provided by the Internet. At the end, we will tie all of these ideas together
by developing a tiny but functional Web server that can serve both static and
dynamic content with text and graphics to real Web browsers.
Every network application is based on the client-server model. With this model, an
application consists of a server process and one or more client processes. A server
manages some resource, and it provides some service for its clients by manipulating
that resource. For example, a Web server manages a set of disk files that it retrieves
and executes on behalf of clients. An FTP server manages a set of disk files that it
stores and retrieves for clients. Similarly, an email server manages a spool file that
it reads and updates for clients.
The fundamental operation in the client-server model is the transaction (Figure 11.1). A client-server transaction consists of four steps:
1. When a client needs service, it initiates a transaction by sending a request to
the server. For example, when a Web browser needs a file, it sends a request
to a Web server.
2. The server receives the request, interprets it, and manipulates its resources in
the appropriate way. For example, when a Web server receives a request from
a browser, it reads a disk file.
3. The server sends a response to the client and then waits for the next request.
For example, a Web server sends the file back to a client.
Aside Client-server transactions versus database transactions
Client-server transactions are not database transactions and do not share any of their properties, such
as atomicity. In our context, a transaction is simply a sequence of steps carried out by a client and a
server.
4. The client receives the response and manipulates it. For example, after a Web
browser receives a page from the server, it displays it on the screen.
It is important to realize that clients and servers are processes and not machines, or hosts as they are often called in this context. A single host can run many
different clients and servers concurrently, and a client and server transaction can
be on the same or different hosts. The client-server model is the same, regardless
of the mapping of clients and servers to hosts."""

### TEXTS ANALYSIS
# Datasets: text_robots; text_networks

# Length
num_chars_robots = len(text_robots)
num_chars_networks = len(text_networks)

# Words
num_words_robots = len(text_robots.split())
num_words_networks = len(text_networks.split())

# Sentences
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

sentences_robots = sent_tokenize(text_robots)
num_sentences_robots = len(sentences_robots)

sentences_networks = sent_tokenize(text_networks)
num_sentences_networks = len(sentences_networks)

# Vocab size
unique_words_robots = set(text_robots.lower().split())
unique_words_networks = set(text_networks.lower().split())

print("*** Robots Text ***")
print("Characters:", num_chars_robots)
print("Words:", num_words_robots)
print("Sentences:", num_sentences_robots)
print("Unique words:", len(unique_words_robots))
print()
print("*** Networks Text ***")
print("Characters:", num_chars_networks)
print("Words:", num_words_networks)
print("Sentences:", num_sentences_networks)
print("Unique words:", len(unique_words_networks))

### COMPARISON OF SUMMARIZATION METHODS

# SUMY - LSA
# Datasets: text_robots; text_networks
# Parameters: 4-sentence summary
# https://www.geeksforgeeks.org/nlp/mastering-text-summarization-with-sumy-a-python-library-overview/

!pip install sumy
import textwrap

from sumy.summarizers.lsa import LsaSummarizer
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.nlp.stemmers import Stemmer
from sumy.utils import get_stop_words

def lsa_summarize(text, sentence_count=2):
    parser = PlaintextParser.from_string(text, Tokenizer("english"))

    # Initialize LSA summarizer
    summarizer = LsaSummarizer(Stemmer("english"))
    summarizer.stop_words = get_stop_words("english")

    summary = summarizer(parser.document, sentence_count)
    return summary

summary1 = lsa_summarize(text_robots, 4)

pretty1 = " ".join(str(sentence) for sentence in summary1)
print()
print("*** Robots text, summarized with SUMY LSA: ***")
print()
print(textwrap.fill(pretty1, width=90))
print()

summary2 = lsa_summarize(text_networks, 4)

pretty2 = " ".join(str(sentence) for sentence in summary2)
print("*** Networks text, summarized with SUMY LSA: ***")
print()
print(textwrap.fill(pretty2, width=90))

# BART Base Booksum Transformer Model
# Datasets: text_robots; text_networks

from transformers import pipeline

summarizer = pipeline("summarization", model="KamilAin/bart-base-booksum")

summary_robots = summarizer(text_robots, max_length=130, min_length=30, do_sample=False)
summary_networks = summarizer(text_networks, max_length=130, min_length=30, do_sample=False)

print()
print("*** Robots Text, summarized with BART Base Booksum: ***")
print()
print(textwrap.fill(summary_robots[0]['summary_text'], width=90))
print()
print("*** Networks Text, summarized with BART Base Booksum: ***")
print()
print(textwrap.fill(summary_networks[0]['summary_text'], width=90))

# BART Base Large CNN Transformer Model
# Datasets: text_robots; text_networks

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

summary_robots = summarizer(text_robots, max_length=130, min_length=30, do_sample=False)
summary_networks = summarizer(text_networks, max_length=130, min_length=30, do_sample=False)

print()
print("*** Robots text, summarized with BART Base Large CNN: ***")
print()
print(textwrap.fill(summary_robots[0]['summary_text'], width=90))
print()
print("*** Networks text, summarized with BART Base Large CNN: ***")
print()
print(textwrap.fill(summary_networks[0]['summary_text'], width=90))

# PEGASUS Transformer Model
# Datasets: text_robots; text_networks

summarizer = pipeline("summarization", model="google/pegasus-xsum")

summary_robots = summarizer(text_robots, max_length=130, min_length=30, do_sample=False, truncation=True)
summary_networks = summarizer(text_networks, max_length=130, min_length=30, do_sample=False, truncation=True)

print()
print("*** Robots text, summarized with PEGASUS: ***")
print()
print(textwrap.fill(summary_robots[0]['summary_text'], width=90))
print()
print("*** Networks text, summarized with PEGASUS: ***")
print()
print(textwrap.fill(summary_networks[0]['summary_text'], width=90))

# T5 Model
# Datasets: text_robots; text_networks

summarizer = pipeline("summarization", model="t5-small")

summary_robots = summarizer(text_robots, max_length=130, min_length=30, do_sample=False)
summary_networks = summarizer(text_networks, max_length=130, min_length=30, do_sample=False)

print()
print("*** Robots text, summarized with T5: ***")
print()
print(textwrap.fill(summary_robots[0]['summary_text'], width=90))
print()
print("*** Networks text, summarized with T5: ***")
print()
print(textwrap.fill(summary_networks[0]['summary_text'], width=90))

### EVALUATION OF SUMMARIZATION METHODS

# Evaluate with ROUGE
# ROUGE1: measures word overlap (unigrams)
# ROUGE2: measures bigram overlap (two-word pairs)
# ROUGEL: measures longest common subsequence (LCS)
# ROUGELsum: same as ROUGEL but designed for multi-sentence summaries
import evaluate

rouge = evaluate.load("rouge")

# Predictions - Robots Text
predictions_sumy_lsa__robots = ["Present-day robotics employs a diverse set of sensors, including cameras, radars, lasers, and microphones to measure the state of the environment and of the people around it; and gyroscopes, strain and torque sensors, and accelerometers to measure the robot’s own state. Robots operate in environments that are partially observable and stochastic: cameras cannot see around corners, and gears can slip. Moreover, the people acting in that same environment are unpredictable, so the robot needs to make predictions about them. For other concepts this chapter breaks new ground, for instance in introducing the continuous version of techniques that we previously saw only in the discrete case."]
predictions_bart_booksum__robots = ["Robots are physical agents that perform tasks by manipulating the physical world. To do so, they are equipped with effectors such as legs, wheels, joints, grippers. Effectors are designed to assert physical forces on the environment. When they do this, a few things may change. For example, a car spins its wheels and makes progress on the road as a result, or a person notices and is nice enough to move out of the way, or even push the button for the robot.Robots operate in environments that are partially observable and stochastic. It is possible to use learning algorithms to learn in a few hours from millions of trials, and the robot cannot risk(and thus cannot learn from) a trial that might cause harm."]
predictions_bart_cnn__robots = ["Robotics brings together many of the concepts we have seen in this book, including probabilistic estimation, perception, planning, unsupervised learning, reinforcement learning, and game theory. Practical robotic systems need to embody prior knowledge about the robot, the physical environment, and the tasks to be performed."]
predictions_pegasus__robots = ["Robotics is a branch of science that deals with the design, development, and operation of machines that are physically capable of performing a variety of tasks."]
predictions_t5__robots = ["robots are physical agents that perform tasks by manipulating the physical world . they are equipped with effectors such as legs, wheels, joints, and grippers . the robot’s state might change, and even the state of the people around the robot might change ."]

# Predictions - Networks Text
predictions_sumy_lsa__networks = ["Any time you browse the Web, send an email message, or play an online game, you are using a network application. For example, processes, signals, byte ordering, memory mapping, and dynamic storage allocation all play important roles. For example, a Web server manages a set of disk files that it retrieves and executes on behalf of clients. An FTP server manages a set of disk files that it stores and retrieves for clients."]
predictions_bart_booksum__networks = ["All network applications are based on the same basic programming model and rely on many of the concepts that you have already learned in our study of systems. For example, every time you browse the Web, send anemail message, or play an online game, you are using a network application. The basic principles of network application are the client-server model and how to write client-service programs that use the services provided by the Internet. At the end of this chapter, we will explain how to build a tiny but functional Web server that can serve both static and dynamic content with text and graphics to real Web browsers."]
predictions_bart_cnn__networks = ["Network applications rely on many of the concepts that you have already learned in our study of systems. You will need to understand the basic clientserver programming model and how to write client-server programs. We will tie all of these ideas together by developing a tiny but functional Web server."]
predictions_pegasus__networks = ["In this course, you will learn how to write a network application. 11.1 The Client-Server Programming Model Every network application is based on the client-server model."]
predictions_t5__networks = ["network applications rely on the same basic programming model . processes, signals, byte ordering, memory mapping, and dynamic storage allocation all play important roles . the client-server model is the same, regardless of the mapping of clients and servers to hosts."]

models = {
    "SUMY LSA": {
        "robots": predictions_sumy_lsa__robots,
        "networks": predictions_sumy_lsa__networks
    },
    "BART Base Booksum": {
        "robots": predictions_bart_booksum__robots,
        "networks": predictions_bart_booksum__networks
    },
    "BART Base Large CNN": {
        "robots": predictions_bart_cnn__robots,
        "networks": predictions_bart_cnn__networks
    },
    "PEGASUS": {
        "robots": predictions_pegasus__robots,
        "networks": predictions_pegasus__networks
    },
    "T5": {
        "robots": predictions_t5__robots,
        "networks": predictions_t5__networks
    }
}

texts = {
    "ROBOTS": text_robots,
    "NETWORKS": text_networks
}

def print_scores(model, text_name, results):
  print()
  print(f"*** ROUGE Scores, {model}, {text_name} ***")
  for k, v in results.items():
    print(f"{k.upper():<10}: {v:.4f}")

for text_name, ref_text in texts.items():
  print()
  print()
  print(f"*** {text_name} TEXT ***")

  for model_name, preds in models.items():
    results = rouge.compute(predictions=preds[text_name.lower()], references=[ref_text])
    print_scores(model_name, text_name, results)

# Evaluate with BERTScore
# Precision: How correct is it / no extra or incorrect info?
# Recall: Didn't miss important info?
# F1: Balanced score between Precision and Recall

from bert_score import score

for text_name, ref_text in texts.items():
    print(f"\n\n*** {text_name} TEXT ***")

    for model_name, preds_dict in models.items():

        preds = preds_dict[text_name.lower()]  # robots / networks
        references = [ref_text] * len(preds)

        P, R, F1 = score(preds, references, lang="en")

        print(f"\n{model_name}")
        print(f"Precision: {P.mean().item():.4f}")
        print(f"Recall:    {R.mean().item():.4f}")
        print(f"F1:        {F1.mean().item():.4f}")